set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/vimfiles/bundle/Vundle.vim/
let path='~/vimfiles/bundle'
call vundle#begin(path)

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'
" " plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" " Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'
" " git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" " The sparkup vim script is in a subdirectory of this repo called vim.
" " Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" " Avoid a name conflict with L9
" Plugin 'user/L9', {'name': 'newL9'}

" molokai (monokai clone) theme
Plugin 'tomasr/molokai'
Plugin 'Raimondi/delimitMate'
Plugin 'scrooloose/nerdtree'
" Plugin 'gorodinskiy/vim-coloresque'
Plugin 'skammer/vim-css-color' " improved colour plugin, faster, less buggy
Plugin 'Shougo/neocomplete.vim'
Bundle 'ntpeters/vim-better-whitespace'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"
"

" default colorscheme
colorscheme molokai
syntax enable
set guifont=Consolas:h10

" auto read when file is changed outside of vim
set autoread

" 7 lines around the cursor when moving vertically with j/k
set so=7

set ruler

set showmatch

set expandtab

set smarttab

set shiftwidth=4
set tabstop=4

set ai
set si

set noeb vb t_vb=
set vb t_vb=

" set foldcolumn=1

set foldmethod=indent

" set number

set history=1000


nmap \e :NERDTreeToggle<CR>

" Shortcut to rapidly toggle `set list`
nmap <leader>l :set list!<CR>

" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:?\ ,eol:¬

" Fix backspace:when
set backspace=indent,eol,start

nnoremap <space> za
vnoremap <space> zf

set backupdir=$TEMP//
set directory=$TEMP//
